https://codeforces.com/contest/1867/problem/D
https://codeforces.com/problemset/problem/1343/D
https://codeforces.com/contest/1476/problem/D
https://codeforces.com/contest/176/problem/B
https://codeforces.com/contest/1870/problem/E
https://codeforces.com/contest/1260/problem/C
https://codeforces.com/contest/1882/problem/D
https://codeforces.com/contest/1381/problem/A2
https://codeforces.com/problemset/problem/1804/C
https://codeforces.com/problemset/problem/1528/B
https://codeforces.com/contest/1848/problem/E
https://codeforces.com/problemset/problem/1312/D
https://codeforces.com/problemset/problem/1332/D
https://codeforces.com/problemset/problem/1301/C
https://codeforces.com/problemset/problem/1406/C
https://codeforces.com/problemset/problem/1422/C
https://codeforces.com/contest/1878/problem/G
https://codeforces.com/problemset/problem/1472/E
https://codeforces.com/problemset/problem/1430/D
https://codeforces.com/problemset/problem/1562/D1
https://codeforces.com/problemset/problem/1583/C
https://codeforces.com/contest/61/problem/E
https://codeforces.com/contest/380/problem/C
https://codeforces.com/problemset/problem/1535/D
https://codeforces.com/contest/1560/problem/E
https://codeforces.com/contest/1525/problem/D   
https://codeforces.com/problemset/problem/1552/C
https://codeforces.com/problemset/problem/1620/C
https://codeforces.com/problemset/problem/1475/D
https://codeforces.com/problemset/problem/1552/D
https://codeforces.com/contest/1038/problem/F
https://codeforces.com/contest/178/problem/B3
https://codeforces.com/contest/1355/problem/C
https://codeforces.com/contest/1877/problem/C
https://codeforces.com/problemset/problem/1443/D
https://codeforces.com/contest/1886/problem/D
https://codeforces.com/contest/1300/problem/D
https://codeforces.com/contest/1468/problem/J
https://codeforces.com/contest/1339/problem/D
https://codeforces.com/problemset/problem/220/B
https://codeforces.com/contest/1881/problem/G
https://codeforces.com/problemset/problem/1796/D
https://codeforces.com/contest/1328/problem/E
https://codeforces.com/contest/1492/problem/D
https://codeforces.com/contest/1613/problem/D
https://codeforces.com/contest/1613/problem/D
https://codeforces.com/contest/1895/problem/D
https://codeforces.com/contest/1658/problem/D2
https://codeforces.com/contest/1428/problem/D
https://codeforces.com/contest/1463/problem/D
https://codeforces.com/contest/1744/problem/F
https://codeforces.com/contest/1192/problem/B
https://codeforces.com/contest/1916/problem/E
